language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
install:
  - composer self-update
  - composer install --no-interaction
script:
  - php vendor/bin/phpunit
after_success:
  - php vendor/bin/coveralls -v
